/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Ap } from "./Ap";
import { ApCountArgs } from "./ApCountArgs";
import { ApFindManyArgs } from "./ApFindManyArgs";
import { ApFindUniqueArgs } from "./ApFindUniqueArgs";
import { DeleteApArgs } from "./DeleteApArgs";
import { ApService } from "../ap.service";
@graphql.Resolver(() => Ap)
export class ApResolverBase {
  constructor(protected readonly service: ApService) {}

  async _apsMeta(@graphql.Args() args: ApCountArgs): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Ap])
  async aps(@graphql.Args() args: ApFindManyArgs): Promise<Ap[]> {
    return this.service.aps(args);
  }

  @graphql.Query(() => Ap, { nullable: true })
  async ap(@graphql.Args() args: ApFindUniqueArgs): Promise<Ap | null> {
    const result = await this.service.ap(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Ap)
  async deleteAp(@graphql.Args() args: DeleteApArgs): Promise<Ap | null> {
    try {
      return await this.service.deleteAp(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
